source 'https://rubygems.org'

gem 'rails',        '~> 3.2.12'
gem 'thin',         '~> 1.5.0'

gem 'sqlite3',      '~> 1.3.7'
gem 'mongo_mapper', '~> 0.12.0'
gem 'mongoid',      '~> 3.1.2'

gem 'vodka', path: '../..', require: 'vodka/server'
