source 'https://rubygems.org'

gem 'rails', '~> 3.2.12'
gem 'will_paginate', '~> 3.0.4'
gem 'sqlite3', '~> 1.3.7'
gem 'thin', '~> 1.5.0'
gem 'multi_json', '~> 1.6.1'

gem 'hren', path: '../..', require: 'hren/server'
