#!/bin/bash

cd spec/dummy
rm -f log/*
RAILS_ENV=production bundle exec rake db:reset 2>&1 > log/setup_db.log
RAILS_ENV=production bundle exec thin start -C config/thin.yml 2>&1 > log/thin_start.log
cd ../..
bundle exec rspec
code=$?
cd spec/dummy
RAILS_ENV=production bundle exec thin stop -C config/thin.yml 2>&1 > log/thin_stop.log
cd ../..
exit $code
