#!/bin/bash
dummy_path="$(pwd)/spec/dummy"
BUNDLE_PATH=$dummy_path/.bundle
BUNDLE_GEMFILE=$dummy_path/Gemfile
RAILS_ENV=development
cd $dummy_path && bundle exec thin start -C $dummy_path/config/thin.yml 2>&1 > $dummy_path/log/thin_start.log
